# Generated by Django 2.2.3 on 2019-09-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.CharField(choices=[('SG', 'Sega Genesis'), ('N', 'Nintendo 64'), ('GC', 'Game Cube'), ('W', 'Wii'), ('SW', 'Switch'), ('PS', 'Playstation 2'), ('PS3', 'Playstation 3'), ('PS4', 'Playstation 4'), ('X', 'Xbox'), ('X1', 'XboxOne')], default='SG', max_length=1)),
            ],
        ),
    ]
