# Generated by Django 2.2.3 on 2019-09-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_console'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogames',
            name='console',
            field=models.ManyToManyField(to='main_app.Console'),
        ),
    ]
